services:
  # Nodo 1: Quito (Principal)
  # Se ejecuta en el puerto 5433 de tu máquina local
  nodo-quito:
    image: postgres
    container_name: taller_quito_db
    environment:
      POSTGRES_USER: taller_user
      POSTGRES_PASSWORD: taller_password_local
      POSTGRES_DB: taller_db
    ports:
      - "5434:5432"
    volumes:
      # Monta únicamente los scripts de inicialización para Quito
      - ./init-db/quito:/docker-entrypoint-initdb.d
    restart: always

  # Nodo 2: Guayaquil
  # Se ejecuta en el puerto 5434 de tu máquina local
  nodo-guayaquil:
    image: postgres
    container_name: taller_guayaquil_db
    environment:
      POSTGRES_USER: taller_user
      POSTGRES_PASSWORD: taller_password_local
      POSTGRES_DB: taller_db
    ports:
      - "5435:5432"
    volumes:
      # Monta únicamente los scripts de inicialización para Guayaquil
      - ./init-db/guayaquil:/docker-entrypoint-initdb.d
    restart: always

  # Nodo 3: Cuenca
  # Se ejecuta en el puerto 5435 de tu máquina local
  nodo-cuenca:
    image: postgres
    container_name: taller_cuenca_db
    environment:
      POSTGRES_USER: taller_user
      POSTGRES_PASSWORD: taller_password_local
      POSTGRES_DB: taller_db
    ports:
      - "5436:5432"
    volumes:
      # Monta únicamente los scripts de inicialización para Cuenca
      - ./init-db/cuenca:/docker-entrypoint-initdb.d
    restart: always

